### ISSUE TITLE
When I switch between 2 coins the price changes [BACKEND]

### ISSUE THREAD

**Issue by Mihay28** [brinc-finance/brinc-bugbounty#20]
When I switch between 2 coins the price changes. Instead to receive 5 DAI for 11.702... BRQ I receive only 4.45467... Big difference  
![Switch](https://user-images.githubusercontent.com/46828978/115127407-eba5cd80-9fde-11eb-803c-551da09bbdb6.png)

**Comment by araskachoi** [comment]
Hello! Thank you for your submission!
This is acutally expected behavior as the amount that you will receive will not be the same for mint and burn. So the price calculation that you are seeing for the burning BRQ -> DAI shows you the amount you would get - which is lower because there is a higher fee to burn than there is to mint.
